services:
  server:
    build:
      dockerfile: ./apps/server/dockerfile
      context: .
    ports:
      - ${PUBLIC_SERVER_PORT}
    healthcheck:
      test: ["CMD", "curl", "http://localhost:${PUBLIC_SERVER_PORT}/api/"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
